Ge fix poetry importlib metadata 0602 (#905)
* Fix poetry, importlib-metadata python 3.8 compabilility issue

Tests have been failing with error:
ERROR: poetry 1.0.5 has requirement importlib-metadata<1.2.0,>=1.1.3;
python_version < "3.8", but you'll have importlib-metadata 1.6.0 which is incompatible.

Adjusted version of importlib-metadata being installed.

* Fetch jquery library from Google, not code.jquery.com

code.jquery.com was causing curl SSL error, so switching to
google libraries as source for jquery.

Co-authored-by: Greg Elin <greg.elin@govready.com>