(WIP) 0.9.1.20 pk 20200601 (#902)
* Update .circleci/config.yml

Temporarily remove building `pip install --user -r requirements_util.txt` since we are not testing the control/utils.

* small docs fixes

* use python lexer for gunicorn.conf.py example

* small doc wording fixes; SQLITE -> SQLite

* remove unneeded 'DEBIAN_FRONTEND=noninteractive'

* another instance of SQLITE->SQLite

* small wording fix

* small wording fix

* choose 'text' lexer instead of 'json' because of '...' (not valid JSON)

* spelling fixes

* Fix poetry, importlib-metadata python 3.8 compabilility issue

Tests have been failing with error:
ERROR: poetry 1.0.5 has requirement importlib-metadata<1.2.0,>=1.1.3;
python_version < "3.8", but you'll have importlib-metadata 1.6.0 which is incompatible.

Adjusted version of importlib-metadata being installed.

* Fetch jquery library from Google, not code.jquery.com

code.jquery.com was causing curl SSL error, so switching to
google libraries as source for jquery.

Co-authored-by: Greg Elin <gregelin@govready.com>
Co-authored-by: Greg Elin <greg.elin@govready.com>