0.9.1.20 (#906)
* Start using `govready-url` parameter in environment.json

To simplify the configuration of deployments, start using
the `govready_url` environment parameter as a replacement
for multiple params of `host`, `port`, and `https`.

For example, in the `local/environment.json` file the single `govready-url` parameter:

```
    {
      "db": "mysql://USER:PASSWORD@HOST:PORT/NAME",
      "govready-url": "http://localhost:8000",
      "debug": false,
      "secret-key": "long_random_string_here"
    }
```

replaces the legacy format that contains two parameters:

```
      {
         "db": "mysql://USER:PASSWORD@HOST:PORT/NAME",
         "host": "localhost:8000",
         "http": false,
         "debug": false,
         "secret-key": "long_random_string_here"
      }
```

During the transition period `govready-url` parameter overrides any setting of `host`, `port`, and `https`
parameters.

* Improve Ubuntu, CentOS from source documentation

Streamline and improve the installation instructions
for Ubuntu from source and CentOS from source.

Make it clearer which user installer is when following
instructions.

Eliminate repetitive notes and warnings.

* Further tweaks to Ubuntu, Centos docs

* More Ubuntu, Centos from source doc improvements

Make a new Step #4 to create the local/environment.json file

* Create local-example directories with fabricated config files

To make installation easier, start creating local-example directories
with prefabricated config files associated with supervisor,
gunicorn, nginx, etc.

This lays the ground work for easier install by copying sample
config files into the local directory.

* Adjust handling of environment.json without host param

Adjust evaluation of environment.json so settings.py
will not crash if host param not present.

* Fix evaluation of host in environment

* Another fix for ALLOWED_HOST

* Another fix for ALLOWED_HOST #2

* Another fix for ALLOWED_HOST #3

* Another fix for EMAIL settings and host #3

* Use govrready-url param in install-govready-q.sh

Parse local/environment.json file in install-govready-q.sh
to get host information to use to set the hostname and port
to launch GovReady-Q.

* Add STATIC_ROOT default to settings.py; collectstatic in install script

Also update install-govready-q.sh to collectstatic.

Make sure jq will be installed in local-examples

* Simplify install with govready-url param, better docs

* Introduce the ``govready_url`` environment parameter as a replacement for
multiple params of ``host``, ``port``, and ``https``. During transition period
``govready-url`` parameter overrides any setting of ``host``, ``port``, and ``https``
parameters. Example below shows the ``local/environment.json`` file using the single
``govready-url`` parameter replacing legacy parameters:

```
    # Preferred local/environment.json file using govready-url parameter

    {
      "db": "mysql://USER:PASSWORD@HOST:PORT/NAME",
      "govready-url": "http://localhost:8000",
      "debug": false,
      "secret-key": "long_random_string_here",
      ...
    }

    # Legacy version local/environment.json file using deprecated host, https parameter

    {
       "db": "mysql://USER:PASSWORD@HOST:PORT/NAME",
       "host": "localhost:8000",
       "https": false,
       "debug": false,
       "secret-key": "long_random_string_here",
       ...
    }
```

* Re-wrote Ubuntu from Source instructions to explain deployment in much greater detail.
* Extend Ubuntu from Source instructions to include Gunicorn, Supervisor, and NGINX
* Created sets of exammple configuration files in ``local-examples`` to make deployment eaiser.

**Deployment changes**

* Created sets of exammple configuration files in ``local-examples`` to make deployment eaiser.
* The ``install-govready-q.sh`` script now reads the ``govready-url`` parameter from ``local/environment.json`` and uses the values to start GovReady-Q on the indicated host and port.

* Correct Ubuntu from Source Supervisor log content

* Update .circleci/config.yml

Commenting out `# pip install --user -r requirements_util.txt` because utils are not part of running deployments.

* Update circleci/config.yml

Removing the following library requirements because they are not necessary for testing GovReady-Q. Not sure if the `#` actually commented out the utils requirements.

            pip install --user -r requirements_mysql.txt
            # pip install --user -r requirements_util.txt

* Update Ubuntu from source with NGINX step

* (WIP) 0.9.1.20 pk 20200601 (#902)

* Update .circleci/config.yml

Temporarily remove building `pip install --user -r requirements_util.txt` since we are not testing the control/utils.

* small docs fixes

* use python lexer for gunicorn.conf.py example

* small doc wording fixes; SQLITE -> SQLite

* remove unneeded 'DEBIAN_FRONTEND=noninteractive'

* another instance of SQLITE->SQLite

* small wording fix

* small wording fix

* choose 'text' lexer instead of 'json' because of '...' (not valid JSON)

* spelling fixes

* Fix poetry, importlib-metadata python 3.8 compabilility issue

Tests have been failing with error:
ERROR: poetry 1.0.5 has requirement importlib-metadata<1.2.0,>=1.1.3;
python_version < "3.8", but you'll have importlib-metadata 1.6.0 which is incompatible.

Adjusted version of importlib-metadata being installed.

* Fetch jquery library from Google, not code.jquery.com

code.jquery.com was causing curl SSL error, so switching to
google libraries as source for jquery.

Co-authored-by: Greg Elin <gregelin@govready.com>
Co-authored-by: Greg Elin <greg.elin@govready.com>

* typo fix: Ubunto -> Ubuntu

* typo fix: Ubunto -> Ubuntu

* 'postgresql-setup' not needed on Ubuntu 20.04

* remove extra blank line

Co-authored-by: Greg Elin <greg.elin@govready.com>
Co-authored-by: Peter Kaminski <peter.kaminski@govready.com>
Co-authored-by: Peter Kaminski <kaminski@istori.com>