Merging 0.9.0.dev into master with Datagrid question type (#809)
* add a Dockerfile for Simple IAM Proxy Server

* small tweak to README.md

* print auth headers on run; add ICAM auth example

* update docs, add docker run for ICAM image

* set 'Host' for destination web server

* Add '/health/request' and '/health/request-headers' command URLs

Taken from https://github.com/GovReady/govready-q/pull/787
See https://github.com/GovReady/govready-q/pull/787/commits for commits.

* make request_headers work with Django < 2.2, as well as >= 2.2

* Fix another timing-dependent test failure (#inputctrl). (#777)

Fixes this error:

```
File "govready/govready-q/siteapp/tests.py", line 416, in test_simple_module
...
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#inputctrl"}
```

* TaskAnswerHistory.get_value() handles dummy properly, fixes #795 (#797)

* Add views.debug route

* Create portfolio for user account added by SSO

* Support environmental param for GovReady Admins in SSO context

* Add debug view remove deprecated upgrade app view

Add debug view
Remove deprecated "upgrade app" view. Confirming upgrading
and app has been handled by dialog boxes for a while and template
was previously removed but the view in views.py lingered. Now removing.

* Update VERSION and CHANGELOG

* Synch in 0.9.0.dev changes that remove depricated

* Add in templates for django performance debug toolbar

* Bump VERSION CHANGELOG

* Synch CHANGELOG for mesosphere updates, SSO logout path, fix show_invite_modal

Reflect changes that were made to synchronize 0.9.0.dev with 0.9.0-mesosphere.

Add in simple SSO logout landing page.

Small fix in main.js to finish show_invite_modal fix for IE11.
Use Math.pow in main.js to fix IE11 error of assign dialogue box.
IE11 does not understand "**" as power of operator, so use Math.pow.
IE11 failing to parse main.js caused IE11 to not show invite dialogue
box because failing to parse main.js caused show_invite_modal to be undefined.

* update jQuery from 3.3.1 to 3.4.1 (latest) (#782)

* Update dependencies

* Remove self-signed cert from 'docker-compose-nginx' (#781)

* build a self-signed cert dynamically

* update docs w/r/t self-signed cert

* Update dependencies

* Add '/health/request' and '/health/request-headers' command URLs (#787)

* remove spurious command call

* remove debugging print() statements

* add short descriptions of health commands

* add '/health/request-headers' URL

Prints HTTP headers which came from web browser.

Example output:

```
{'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
 'Accept-Encoding': 'gzip, deflate, br',
 'Accept-Language': 'en-US,en;q=0.9',
 'Connection': 'close',
 'Content-Length': '',
 'Content-Type': 'text/plain',
 'Cookie': 'iam_session=username=testuser&email=testuser%40example.com; '
           'csrftoken=hrAm5pzGjAc09EGdS0zAHzQza68SWqkMM0l4saBTzwgqVpwj2nUxzafLIv7SpmXV; '
           'sessionid=kipus910b91fjac1m0jb85ltf0imf3sg',
 'Host': 'localhost:8000',
 'Iam-Email': 'testuser@example.com',
 'Iam-Username': 'testuser',
 'Sec-Fetch-Mode': 'navigate',
 'Sec-Fetch-Site': 'none',
 'Sec-Fetch-User': '?1',
 'Upgrade-Insecure-Requests': '1',
 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) '
               'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 '
               'Safari/537.36',
 'X-Forwarded-For': '127.0.0.1'}
```

* Added '/health/request' command URL

'/health/request' prints system information, so DEBUG is required to be true.

* Install entire sqlite3 command instead of just sqlite3 library. (#786)

For users who use the sqlite3 command inside a Docker container, this
commit makes sure to install the whole command, instead of just the
library.  It runs sqlite3 during the Docker build, as a test to make
sure it's working.

We use the least recent sqlite3 version acceptable to Django (v3.8.3)
instead of anything more recent, after observing large and small
compatibility problems between Django or other libraries and more
recent sqlite versions (3.22.x and up; previous versions weren't
tested). v3.8.5 was probably fine, but v3.8.3 seems more conservative,
and is still acceptable to Django.

* Loads $VENDOR from local/environment.json (if it exists) (#778)

If local/environment.json doesn't exist, it uses a default.

Uses python to load the JSON, doesn't require other libraries or utilities.

Code tested under these conditions:

* python2 AND python3
* local/environment.json exists AND local/environment.json does not exist
* 'static' key exists in local/environment.json AND 'static' key does not exist in local/environment.json

* Add a Docker build-time option to use Gunicorn instead of uWSGI (#779)

* use gunicorn instead of uwsgi

* Add a Docker build-time option to use Gunicorn instead of uWSGI.

The build-time options are documented in `deployment/docker/README.md`.

* Fix duplicated libraries

Co-authored-by: Greg Elin <gregelin@govready.com>

* Synchronizing with master

* Synch with Master to fix siteapp/tests.py

* Merge in datagrid question type (#804)

Creating `datagrid` question type

Created datagrid question type by copying code of multile-choice question type.
columns.

* Add `jsGrid` to act as datagrid user interface.
* Stor datagrid question data in database.
* Display datagrid answer type in review page.
* Render datagrid in artifact templates.
* Widen question area for datagrid questions
* Use 'field' nomenclature for datagrid and not 'choice'
* Sync with 0.9.0.dev-mesosphere
* Fix multiple-choice answer verification bug caused by datagrid (this took a while to track down)
* Further synchronization and testing with master and 0.9.0.dev
in preparation of merging; comment out datagrid tests
* Updated docs (to a degree)

TODO:
- Add tests
- Handle imputes with datagrid
- Update docs further

modified:   CHANGELOG.md
modified:   VERSION
modified:   docs/source/Automation.md
modified:   docs/source/Schema.md
modified:   fixtures/modules/other/simple_project/question_types_choice.yaml
modified:   guidedmodules/answer_validation.py
modified:   guidedmodules/app_loading.py
modified:   guidedmodules/models.py
modified:   guidedmodules/module_logic.py
modified:   guidedmodules/tests.py
modified:   q-files/vendors/govready/govready-q-files-startpack/q-files/System-Description-Demo/system_basics_technical.yaml
modified:   siteapp/management/commands/test_screenshots.py
modified:   siteapp/tests.py
modified:   templates/authoring-tool-modal.html
modified:   templates/project-api.html
modified:   templates/question.html
modified:   testmocking/data_management.py

* Fix authoring-tool-modal.html

* typo fix: huma -> human

* typo fix: dictionat -> dictionary

* typo fixes

browsers provides -> browsers provide
develpers -> developers

* typo fixes

browsers provides -> browsers provide
develpers -> developers

* Fixes for synchronizing with Master

Remove organization reference from profile module
Fix issue with selecting review page
Synchronize siteapp/tests.py

* Synchronize with master branch

* Update SQLite to 3.8.5

* Fix VERSION, CHANGELOG

* Update VERSION CHANGELOG

* typo fix: typre -> type

Co-authored-by: Peter Kaminski <kaminski@istori.com>
Co-authored-by: Peter Kaminski <peter.kaminski@govready.com>
Co-authored-by: Greg Elin <greg.elin@govready.com>